theme: minima
title: Toy Stuff
email: jim.toy@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Age is an issue of mind over matter. If you don't mind, it doesn't matter. - Twain
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jim_toy
github_username:  jimtoy
header_pages:
  - posts.md
  - resume.md
  - about.md
